============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /Users/jack/249B_Project/pyco-dev-thesis
plugins: timeout-1.3.3
timeout: 1000.0s
timeout method: signal
timeout func_only: False
collected 1 item

pyco/tests/test_spi.py E

==================================== ERRORS ====================================
_____________________ ERROR at setup of test_adc4_int[-1] ______________________

    @pytest.fixture
    def counter():
        '''
        counter
        '''
        comp = Counter('Counter')
>       return LibraryComponent('Counter', comp)

pyco/tests/test_spi.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyco/library.py:600: in __init__
    if verify and not self.contract.is_consistent():
../pycolite-dev-thesis/pycolite/contract.py:606: in is_consistent
    return strategy_obj.check_consistency()
../pycolite-dev-thesis/pycolite/nuxmv.py:887: in check_consistency
    delete_file=self.delete_files)
../pycolite-dev-thesis/pycolite/nuxmv.py:156: in is_empty_formula
    tool_location=tool_location, delete_file=delete_file)
../pycolite-dev-thesis/pycolite/nuxmv.py:254: in verify_tautology
    return_trace=return_trace)
../pycolite-dev-thesis/pycolite/nuxmv.py:213: in verify_tautology_smv
    stderr=STDOUT, )
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/Users/jack/249B_Project/pycolite-dev-thesis/resources/nuXmv-1.1.1-Darwin/bin/nuXmv', '-source', '/Users/jack/249B_Project/pycolite-dev-thesis/resources/nuXmv-1.1.1-Darwin/bin/verify_tautology.cmd', '/tmp/E9Nyt7.smv'],)
kwargs = {'stderr': -2}, process = <subprocess.Popen object at 0x106f27e90>
output = "*** This is nuXmv 1.1.1 (compiled on Wed Jun  1 10:19:55 2016)\n*** Copyright (c) 2014-2016, Fondazione Bruno Kessler...aborting 'source /Users/jack/249B_Project/pycolite-dev-thesis/resources/nuXmv-1.1.1-Darwin/bin/verify_tautology.cmd'\n"
unused_err = None, retcode = 255
cmd = ['/Users/jack/249B_Project/pycolite-dev-thesis/resources/nuXmv-1.1.1-Darwin/bin/nuXmv', '-source', '/Users/jack/249B_Project/pycolite-dev-thesis/resources/nuXmv-1.1.1-Darwin/bin/verify_tautology.cmd', '/tmp/E9Nyt7.smv']

    def check_output(*popenargs, **kwargs):
        r"""Run command with arguments and return its output as a byte string.
    
        If the exit code was non-zero it raises a CalledProcessError.  The
        CalledProcessError object will have the return code in the returncode
        attribute and output in the output attribute.
    
        The arguments are the same as for the Popen constructor.  Example:
    
        >>> check_output(["ls", "-l", "/dev/null"])
        'crw-rw-rw- 1 root root 1, 3 Oct 18  2007 /dev/null\n'
    
        The stdout argument is not allowed as it is used internally.
        To capture standard error in the result, use stderr=STDOUT.
    
        >>> check_output(["/bin/sh", "-c",
        ...               "ls -l non_existent_file ; exit 0"],
        ...              stderr=STDOUT)
        'ls: non_existent_file: No such file or directory\n'
        """
        if 'stdout' in kwargs:
            raise ValueError('stdout argument not allowed, it will be overridden.')
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
        output, unused_err = process.communicate()
        retcode = process.poll()
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd, output=output)
E           CalledProcessError: Command '['/Users/jack/249B_Project/pycolite-dev-thesis/resources/nuXmv-1.1.1-Darwin/bin/nuXmv', '-source', '/Users/jack/249B_Project/pycolite-dev-thesis/resources/nuXmv-1.1.1-Darwin/bin/verify_tautology.cmd', '/tmp/E9Nyt7.smv']' returned non-zero exit status 255

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py:573: CalledProcessError
=========================== 1 error in 0.62 seconds ============================
============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /Users/jack/249B_Project/pyco-dev-thesis
plugins: timeout-1.3.3
timeout: 1000.0s
timeout method: signal
timeout func_only: False
collected 1 item

pyco/tests/test_spi.py [['ready', 'adcbit_2', 'adcbit_3', 'adcbit_0', 'adcbit_1']]
Instantiate Solvers...
14
14
Process RefinementChecker-1:1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/jack/249B_Project/pyco-dev-thesis/pyco/z3_thread_manager.py", line 267, in run
    self.manager.result_queue, self.terminate_event)
  File "/Users/jack/249B_Project/pyco-dev-thesis/pyco/counterxample_analysis.py", line 334, in counterexample_analysis
    max_depth=manager.max_depth)
  File "/Users/jack/249B_Project/pyco-dev-thesis/pyco/counterxample_analysis.py", line 1597, in exists_forall_learner
    l_passed, ntrace = verify_tautology_smv(smv, return_trace=True)
  File "/Users/jack/249B_Project/pycolite-dev-thesis/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 567, in check_output
    output, unused_err = process.communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
*Process SinglePortSolver-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/jack/249B_Project/pyco-dev-thesis/pyco/z3_single_port_solver.py", line 148, in run
    spec, contract_list, params_assign) = thread_manager.synthesize()
  File "/Users/jack/249B_Project/pyco-dev-thesis/pyco/z3_thread_manager.py", line 135, in synthesize
    return self.quit(wait=True)
  File "/Users/jack/249B_Project/pyco-dev-thesis/pyco/z3_thread_manager.py", line 161, in quit
    thread.join()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py:117: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --fulltrace)
======================== no tests ran in 18.79 seconds =========================
